{"uid":"5dd2582d6d3f9641","name":"AccessToDB.Tests.SlopesRepositoryTests.TestDeleteSlopeByIDAsyncFailsWhenIDNotExists(slopeID: 145)","fullName":"AccessToDB.Tests.SlopesRepositoryTests.TestDeleteSlopeByIDAsyncFailsWhenIDNotExists(slopeID: 145)","historyId":"AccessToDB.Tests.SlopesRepositoryTests.TestDeleteSlopeByIDAsyncFailsWhenIDNotExists(slopeID: 145)","time":{"start":1665467729902,"stop":1665467732195,"duration":2293},"status":"failed","statusMessage":"Assert.Throws() Failure\r\nExpected: typeof(AccessToDB.Exceptions.SlopeExceptions.SlopeNotFoundException)\r\nActual:   typeof(AccessToDB.Exceptions.SlopeExceptions.SlopeDeleteException): Exception of type 'AccessToDB.Exceptions.SlopeExceptions.SlopeDeleteException' was thrown.\nException of type 'AccessToDB.Exceptions.SlopeExceptions.SlopeDeleteException' was thrown.","statusTrace":"   at AccessToDB.RepositoriesTarantool.TarantoolSlopesRepository.DeleteSlopeByIDAsync(UInt32 slopeID) in C:\\Users\\alena\\Desktop\\7_sem\\testing_and_debugging\\SkiResort\\AccessToDB\\TarantoolRepositories\\TarantoolSlopesRepository.cs:line 122\r\n   at AccessToDB.Tests.SlopesRepositoryTests.<>c__DisplayClass13_0.<<TestDeleteSlopeByIDAsyncFailsWhenIDNotExists>b__0>d.MoveNext() in C:\\Users\\alena\\Desktop\\7_sem\\testing_and_debugging\\SkiResort\\AccessToDB.Tests\\SlopesRepositoryTests.cs:line 142\r\n--- End of stack trace from previous location ---\r\n   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/xunit.assert/Asserts/Record.cs:line 104\n   at AccessToDB.RepositoriesTarantool.TarantoolSlopesRepository.DeleteSlopeByIDAsync(UInt32 slopeID) in C:\\Users\\alena\\Desktop\\7_sem\\testing_and_debugging\\SkiResort\\AccessToDB\\TarantoolRepositories\\TarantoolSlopesRepository.cs:line 122\r\n   at AccessToDB.Tests.SlopesRepositoryTests.<>c__DisplayClass13_0.<<TestDeleteSlopeByIDAsyncFailsWhenIDNotExists>b__0>d.MoveNext() in C:\\Users\\alena\\Desktop\\7_sem\\testing_and_debugging\\SkiResort\\AccessToDB.Tests\\SlopesRepositoryTests.cs:line 142\r\n--- End of stack trace from previous location ---\r\n   at Xunit.Assert.RecordExceptionAsync(Func`1 testCode) in /_/src/xunit.assert/Asserts/Record.cs:line 104","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"thread","value":".NET Long Running Task"},{"name":"host","value":"DESKTOP-TJ9D65N"},{"name":"testClass","value":"AccessToDB.Tests.SlopesRepositoryTests"},{"name":"testMethod","value":"AccessToDB.Tests.SlopesRepositoryTests.TestDeleteSlopeByIDAsyncFailsWhenIDNotExists(slopeID: 145)"},{"name":"package","value":"AccessToDB.Tests.SlopesRepositoryTests"},{"name":"suite","value":"SlopesRepositorySuite"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5dd2582d6d3f9641.json","parameterValues":[]}